
version: '2'

tasks:
  build:
    cmds:
      - packr build -o dist/server

  run:
    deps: [build]
    dir: dist
    cmds:
      - ./server

  deploy:
    deps: [build]
    cmds:
      - rsync -arv dist/server root@peerpx.com:/var/www/peerpx.social/
      - rsync -arv dist/www root@peerpx.com:/var/www/peerpx.social/
      - ssh root@peerpx.com chown -R www-data /var/www/peerpx.social
      - ssh root@peerpx.com systemctl restart peerpx.social

  test:
    cmds:
      - go test ./...
