
version: '2'

tasks:
  build:
    cmds:
      - go build -o ../etc/dist/server

  run:
    deps: [build]
    dir: ../etc/dist
    cmds:
      - ./server

  deploy:
    deps: [build]
    cmds:
      - rsync -arv ../dist/ peerpx@peerpx.com:/home/peerpx/


  test:
    cmds:
      - go test ./...
